#!/bin/bash

customize_ruby() {

  e_header "Installing rubies along with gems ..."
  ruby-install ruby 1.9
  ruby-install ruby 2.1
  ruby-install jruby

  e_header "Installing global ruby gems ..."

  local -a rubies=(
    'ruby-1.9'
    'ruby-2.1'
    'jruby'
  )

  local -a global_gems=(
    'bundler'
    'pry'
    'pry-debugger'
    'interactive_editor'
    'awesome_print'
    'github-markup'
    'tilt'
  )

  for ruby_version in "${rubies[@]}"
  do
    chruby $ruby_version

    printf "$(tput setaf 7)Installing default gems for $ruby_version\033[m\n"
    gem env

    for global_gem in "${global_gems[@]}"
    do
      if [[ "$ruby_version" == "jruby" && ("$global_gem" == "github-markup" || "$global_gem" == "pry-debugger") ]]; then
        printf "$(tput setaf 136)Skipped installing $global_gem (not supported on $ruby_version)\033[m\n"
      elif [[ "$ruby_version" == "ruby-2.1" && "$global_gem" == "pry-debugger" ]]; then
        gem install pry-byebug
      else
        gem install $global_gem
      fi
    done
  done
}
