#!/bin/bash
# shellcheck disable=SC1090

load_dotfiles() {
  local -r dotfiles_directory=${1:-"$HOME/src/dotfiles"}

  declare -a files=(
    "$dotfiles_directory"/lib/colors.sh     # Solarized colors
    "$dotfiles_directory"/bash/bash_options # Options
    "$dotfiles_directory"/bash/bash_exports # Exports
    "$dotfiles_directory"/bash/bash_aliases # Aliases
    "$HOME"/.iterm2_shell_integration.bash  # Activate iTerm2 shell extensions
    "$HOME"/.bash_profile.local             # Local and private settings not under version control (e.g. git credentials)
    "$dotfiles_directory"/bash/bash_paths   # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
    "$dotfiles_directory"/bash/bash_prompt  # Custom bash prompt
    "$dotfiles_directory"/lib/fzf.sh        # fzf customization
  )

  # if these files are readable, source them
  for index in ${!files[*]}; do
    [[ -r ${files[$index]} ]] && source "${files[$index]}"
  done

  # source Bash completion (installed via Homebrew)
  # only use `brew` after it has been added to the PATH
  if [[ -r $(brew --prefix)/etc/bash_completion ]]; then
    source "$(brew --prefix)"/etc/bash_completion
  fi

  # set 256 color profile where possible
  if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
  elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
  fi
}

load_dotfiles "$HOME/src/dotfiles"

source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh

unset load_dotfiles
