#!/bin/bash

# bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
  "$HOME/.local/bin"
  "$HOME/.cargo/bin"
  "$HOME/Library/Python/3.7/bin"
  "/usr/local/opt/ruby@2.5/bin"
  "/usr/local/lib/ruby/gems/2.5.0/bin"
  "/usr/local/opt/bison/bin"
  "/usr/local/opt/icu4c/bin"
  "/usr/local/opt/icu4c/sbin"
  "/usr/local/opt/openssl/bin"
  "/usr/local/opt/sqlite/bin"
  "/usr/local/bin" # Ensure that this bin always takes precedence over `/usr/bin`
  "/usr/local/opt/icu4c/sbin"
  "/usr/local/sbin"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
  "/usr/bin"
  "$HOME/bin"
  "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
  "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}; do
  if [ -d "${dirs_to_prepend[$index]}" ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dirs_to_prepend[$index]}:$PATH"
  fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}; do
  if [ -d "${dirs_to_append[$index]}" ]; then
    # If these bins exist, then append them to existing PATH
    PATH="$PATH:${dirs_to_append[$index]}"
  fi
done

unset dirs_to_prepend dirs_to_append

export PATH
