#!/bin/bash

# bash_config

export DISABLE_AUTO_TITLE=true

export MYVIMRC=~/src/dotfiles/vimrc

# Make vim the default editor
export EDITOR="vim"

# Ignore commands that start with spaces and duplicates
export HISTCONTROL="erasedups:ignoreboth"

# Increase the maximum number of commands to remember
# (default is 500)
export HISTSIZE=32768

# Increase the maximum number of lines contained in the history file
# (default is 500)
export HISTFILESIZE=$HISTSIZE

# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
export HISTTIMEFORMAT='%F %T '

# Prefer US English and use UTF-8 encoding
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Configure junegunn/fzf
export FZF_DEFAULT_COMMAND='rg --files -g ""'
export FZF_DEFAULT_OPTS='--height 40% --reverse --border --multi --no-hscroll --tabstop=2 --cycle --inline-info'
