#!/bin/bash

# inputrc

# Enable incremental history search with up/down arrows (also Readline goodness)
# Keep left/right cursor keys intact
"\e[A": history-search-backward
"\e[B": history-search-forward
"\e[C": forward-char
"\e[D": backward-char

# Try to stay at the same the cursor position when moving through the history.
set history-preserve-point on

# Never ring any sort of bell during line reading
set bell-style none

# Ignore case when matching and completing paths
set completion-ignore-case On

# Treat underscores and hyphens the same way for completion purposes
set completion-map-case On

# Show me up to 5,000 completion items, don't be shy
set completion-query-items 5000

# Don't display control characters like ^C if I input them
set echo-control-characters Off

# Use vim bindings
set editing-mode vim

# Expand tilde to full path on completion
set expand-tilde On

# When completing directories, add a trailing slash
set mark-directories On

# Do the same for symlinked directories
set mark-symlinked-directories On

# Don't paginate possible completions
set page-completions Off

# Show multiple completions on first tab press
set show-all-if-ambiguous On

# Don't re-complete already completed text in the middle of a word
set skip-completed-text On

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Show extra file information when completing, like ls -F does.
set visible-stats on
